export const SITE_TITLE = 'opik.dev';
export const SITE_DESCRIPTION = 'Personal website of Taufik Bahri (Opik) - Software developer focused on building minimalist, efficient web applications and exploring AI technologies.';
export const SITE_URL = 'https://opik.dev';
export const SITE_AUTHOR = 'Taufik Bahri';
export const SITE_AUTHOR_NICKNAME = 'Opik';
export const SITE_AUTHOR_TWITTER = '@opikdev';
export const SITE_AUTHOR_X_URL = 'https://x.com/opikdev';
export const SITE_AUTHOR_LINKEDIN_URL = 'https://www.linkedin.com/in/taufik-bahri';
export const SITE_AUTHOR_EMAIL = 'hi@opik.dev';
